version: '3.8'

services:
  api-build:
    container_name: simple_nestjs_api_build
    restart: "no"
    build:  
      context: docker/api
      dockerfile: ./Dockerfile
    user: "node"
    tty: true
    volumes:
      - ./:/app
    command: >
      bash -c "npm ci
      && rm -rf dist
      && npm run build"

  api-run:
    container_name: simple_nestjs_api_run
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    build:  
      context: docker/api
      dockerfile: ./Dockerfile
    user: "node"
    tty: true
    volumes:
      - ./:/app
    ports:
      - ${PORT}:3000
      - ${DEBUG_PORT}:9229
    command: ["npm", "run", "start:prod"]

  postgres:
    container_name: simple_nestjs_postgres
    restart: unless-stopped
    build:
      dockerfile: docker/postgres/Dockerfile
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

  redis:
    container_name: simple_nestjs_redis
    restart: unless-stopped
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./docker/redis/data:/data